# Generated by Django 5.0.4 on 2024-06-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='no tags', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
