# Generated by Django 5.0.6 on 2024-06-10 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['done', '-created_at']},
        ),
    ]
